---
title: hireserge
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: serge@hireserge.com
description: Professional site of Serge Lobatch, a Product Manager based in Seattle, WA.
baseurl: ''
url: ''
markdown: kramdown
permalink: "/slog/:year/:i_month/:i_day/:title"
sass:
  sass_dir: _sass
exclude:
- vendor
