# Site settings
title: hireserge
email: serge@hireserge.com
description: "Learn about Serge Lobatch, a Product Manager, based in NYC."
baseurl: ""
#baseurl: ""
url: ""

# Default build settings
markdown: kramdown
# permalink: /slog/

# Serge's build settings
permalink: /slog/:year/:i_month/:i_day/:title

# Sass directory
sass:
  sass_dir: _sass

exclude: [vendor]
