# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hire Serge
email: serge@hireserge.com
description: > # this means to ignore newlines until "baseurl:"
  Learn more about Serge Lobatch, a NYC-based Product Manager.
baseurl: "/jekyll-branched" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
twitter_username: slobatch
github_username:  slobatch

# Build settings
markdown: kramdown
exclude: ["README.md"]
